# Generated by Django 6.0.4 on 2026-05-12 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='seats_in_row',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(26)]),
        ),
    ]
