# Generated by Django 6.0.4 on 2026-05-11 11:33

import django.db.models.deletion
import flight.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(db_index=True, default=flight.models.generate_booking_reference, editable=False, help_text='Auto-generated 6-character booking reference (e.g., ABC123)', max_length=6, unique=True)),
                ('passenger_first_name', models.CharField(max_length=50)),
                ('passenger_last_name', models.CharField(max_length=50)),
                ('passenger_passport_code', models.CharField(max_length=20)),
                ('seat_number', models.CharField(max_length=10)),
                ('ticket_class', models.CharField(choices=[('ECO', 'Economy'), ('BUS', 'Business'), ('FIR', 'First Class')], default='ECO', max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('baggage_weight', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('BOK', 'Booked'), ('PAI', 'Paid'), ('CHK', 'Checked-in'), ('CAN', 'Cancelled')], default='BOK', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(db_index=True, max_length=10, unique=True)),
                ('start_datetime', models.DateTimeField()),
                ('approximate_duration', models.DurationField()),
                ('status', models.CharField(choices=[('SCH', 'Scheduled'), ('DEL', 'Delayed'), ('DEP', 'Departed'), ('ARR', 'Arrived'), ('CAN', 'Cancelled')], default='SCH', max_length=3)),
                ('terminal', models.CharField(blank=True, max_length=10, null=True)),
                ('gate', models.CharField(blank=True, max_length=10, null=True)),
                ('price_economy', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('price_business', models.DecimalField(decimal_places=2, default=250.0, max_digits=10)),
                ('price_first_class', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('airline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='airport.airline')),
                ('airplane', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='airport.airplane')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_flights', to='airport.airport')),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_flights', to='airport.airport')),
            ],
        ),
    ]
