# Generated by Django 6.0.4 on 2026-05-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='price_business',
            field=models.DecimalField(decimal_places=2, default=250.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='price_economy',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='price_first_class',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
    ]
