# Generated by Django 6.0.4 on 2026-05-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_seat_per_flight',
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['CAN']), _negated=True), fields=('flight', 'seat_number'), name='unique_seat_per_flight'),
        ),
    ]
