# Generated by Django 6.0.4 on 2026-05-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_flight_price_business_flight_price_economy_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('flight', 'seat_number'), name='unique_seat_per_flight'),
        ),
    ]
