# Generated by Django 6.0.4 on 2026-05-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_remove_ticket_unique_seat_per_flight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('BOK', 'Booked'), ('PAI', 'Paid'), ('CHK', 'Checked-in'), ('CAN', 'Cancelled'), ('EXP', 'Expired')], default='BOK', max_length=3),
        ),
    ]
